color_list1 = set(["black","green","blue","white"])
color_list2 = set(["red","orange","black","white"])
print("colo-list not contained in color_list2 are:")
print(color_list1.difference(color_list2))
print("colo-list not contained in color_list1 are:")
print(color_list2.difference(color_list1))
